### PR TITLE
Nav bar fix

### LINKED ISSUE #7: There is bunch of odd text in the NavBar

### PR DESCRIPTION
**Pull request by tolgabalci**
This fixes #7 

-  Removed text in navbar
-  Made component one's button red

### CODE REVIEW

**Comment by tolgabalci** [comment]
This looks great, but should we really merge?

**Comment by bemch24** [comment]
Looks great!  Best code ever!

**Comment by dfillingame** [comment]
Did you review this with the business owners

**Comment by oscorp82** [comment]
And you know, I'm tired ... I'm so tired of pretending like my life isn't
perfect and bitchin' and just winning every second .... And I'm not perfect
and bitchin', and just delivering the goods at every frickin' turn. And
therefore there's nothing in the middle. I don't live in the middle
anymore. That's where you get slaughtered. That's where you get embarrassed
in front of the prom queen. And it's just not an option.

Check it, Alex, I embarrassed him in front of his children and the world by
healing at a pace that his unevolved mind can't process. Okay ... last I
checked, Chaim, I've spent close to the last decade, I don't know,
effortless and magically converting your tin cans into pure gold.

**Comment by bemch24** [comment]
Who cares about the business owners anyway

**Comment by garyfostergh** [comment]
my change was great. not sure about Tolga's.

**Pull request merged**
